---
inherit_gem:
    syntax_tree: config/rubocop.yml

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Exclude:
    - Rakefile
    - "**/*.rake"

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

# Style/ClassAndModuleChildren:
#   Exclude:
#     - test/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/NegatedIf:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
