#!/usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rubydns"
  gem "logger"
end

INTERFACES = [[:udp, "0.0.0.0", 53], [:tcp, "0.0.0.0", 53]].freeze

IN = Resolv::DNS::Resource::IN

# Use Cloudflare DNS upstream for name resolution.
UPSTREAM = RubyDNS::Resolver.new([[:udp, "1.1.1.3", 53], [:tcp, "1.0.0.3", 53]])

RubyDNS.run_server(INTERFACES) do
  on(:start) do
    @logger = Logger.new($stderr)

    if ARGV.include?("-d") || ARGV.include?("--debug")
      @logger.debug!
      $stderr.sync = true
    end
  end

  # Match any pco or churchcenter subdomain
  match(/(pco|churchcenter).test/, IN::A) do |transaction|
    transaction.respond!("127.0.0.1")
  end

  # Default DNS handler
  otherwise { |transaction| transaction.passthrough!(UPSTREAM) }
end
